import crypto from 'node:crypto';
import { getPostgresPool } from './db/postgres';
import { governRevenueAction } from './revenue-control-plane';
export const GLORIFIER_EAS_VERSION='GEAS-1.2';
export const ENTERPRISE_ARCHITECTURE_PRINCIPLES=[
'well-architected-quality-gates','data-foundation-and-lineage','semantic-business-layer','ai-gateway-and-policy-enforcement',
'multi-agent-orchestration','grounded-knowledge-and-rag','tool-and-protocol-interoperability','model-lifecycle-and-evaluation',
'observability-and-operational-excellence','security-privacy-and-responsible-ai','reliability-and-resilience','cost-and-finops',
'hybrid-multicloud-portability','continuous-assessment-and-improvement','enterprise-strategy','business-capabilities','value-streams','application-portfolio','integration-and-api','networking','distributed-systems','microservices','event-driven','serverless','containers-kubernetes','edge-computing','iot-ot','blockchain-web3','digital-twin','quantum-readiness','developer-platforms','supply-chain-security','zero-trust','privacy-engineering','disaster-recovery','business-continuity','knowledge-architecture','rag-and-agentic-ai','ai-gateway','agent-platform','model-serving','gpu-infrastructure','mlops','llmops','data-mesh','data-fabric','lakehouse','streaming','data-products','master-data','metadata-management','finops','greenops','sustainability','observability','sre','chaos-engineering','vendor-risk','open-source-governance','regulatory-technology'
] as const;
export function getEnterpriseArchitectureScientistPolicy(){return{version:GLORIFIER_EAS_VERSION,
sources:['Google Cloud','Microsoft Azure','IBM','The Open Group TOGAF','NIST','CNCF','IETF','W3C','OWASP','ISO/IEC','Cloud Security Alliance','Linux Foundation','OpenTelemetry','Kubernetes','public engineering research and authoritative vendor documentation'],
refinedArchitecture:['Human Authority','AI CEO','Policy/Compliance/Security Governance','Architecture Quality Gates','AI Gateway','Provider-Neutral Orchestration','Specialist Agents','Knowledge/Data Foundation','Semantic Business Layer','Tools/MCP/A2A/OpenAPI','Model Evaluation & Lifecycle','Observability/SRE','FinOps/Cost Intelligence','Evidence & Lineage','Revenue Control Plane'],
principles:[...ENTERPRISE_ARCHITECTURE_PRINCIPLES],continuousImprovement:true,scope:'global architecture intelligence across business, information, application, technology, security, AI, data, cloud, platform, network, integration, operations, IoT/edge, financial and emerging architectures',humanAuthority:true,autonomousIrreversibleActions:false,certificationClaimAllowed:false};}
export const GEAS_CONTINUOUS_WORKSTREAMS=['architecture-health','reliability','security','data-lineage','ai-lifecycle','model-evaluation','observability','finops','integration-drift','dependency-risk','technical-debt','disaster-recovery','capacity','performance','sustainability','governance'];
export async function initializeEnterpriseArchitectureScientist(){await getPostgresPool().query(`CREATE TABLE IF NOT EXISTS glorifier_architecture_assessments(id TEXT PRIMARY KEY,source_family TEXT NOT NULL,domain TEXT NOT NULL,finding TEXT NOT NULL,evidence_refs JSONB NOT NULL DEFAULT '[]',status TEXT NOT NULL DEFAULT 'observed',priority TEXT NOT NULL DEFAULT 'normal',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()); CREATE TABLE IF NOT EXISTS glorifier_architecture_watchlist(id TEXT PRIMARY KEY,domain TEXT NOT NULL,subject TEXT NOT NULL,cadence_minutes INTEGER NOT NULL DEFAULT 1440,enabled BOOLEAN NOT NULL DEFAULT TRUE,last_run_at TIMESTAMPTZ,next_run_at TIMESTAMPTZ); CREATE TABLE IF NOT EXISTS glorifier_architecture_improvement_cycles(id TEXT PRIMARY KEY,assessment_id TEXT NOT NULL,governance_event_id TEXT,governance_cycle_id TEXT,status TEXT NOT NULL,baseline JSONB NOT NULL DEFAULT '{}'::jsonb,target JSONB NOT NULL DEFAULT '{}'::jsonb,verification JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());`);}
export async function recordArchitectureAssessment(input:{sourceFamily:string;domain:string;finding:string;evidenceRefs?:string[];priority?:string}){await initializeEnterpriseArchitectureScientist();const r=await getPostgresPool().query(`INSERT INTO glorifier_architecture_assessments(id,source_family,domain,finding,evidence_refs,priority) VALUES(gen_random_uuid()::text,$1,$2,$3,$4,$5) RETURNING *`,[input.sourceFamily,input.domain,input.finding,JSON.stringify(input.evidenceRefs||[]),input.priority||'normal']);return r.rows[0];}
export async function runArchitectureHealthCheck(){await initializeEnterpriseArchitectureScientist();const db=getPostgresPool();const [a,w]=await Promise.all([db.query('SELECT COUNT(*)::int count FROM glorifier_architecture_assessments WHERE status IN (\\'observed\\',\\'open\\')'),db.query('SELECT COUNT(*)::int count FROM glorifier_architecture_watchlist WHERE enabled=true')]);return{version:GLORIFIER_EAS_VERSION,continuous:true,activeFindings:Number(a.rows[0].count),activeWatchlists:Number(w.rows[0].count),workstreams:[...GEAS_CONTINUOUS_WORKSTREAMS],nextCycle:'continuous/event-driven plus scheduled assessments'};}
export async function getEnterpriseArchitectureSnapshot(){await initializeEnterpriseArchitectureScientist();const r=await getPostgresPool().query(`SELECT domain,COUNT(*)::int count FROM glorifier_architecture_assessments GROUP BY domain ORDER BY count DESC`);return{version:GLORIFIER_EAS_VERSION,policy:getEnterpriseArchitectureScientistPolicy(),assessmentCounts:r.rows};}

export async function governArchitectureFinding(input:{assessmentId:string; objective:string; capability?:string; evidenceRefs?:string[]; baseline?:Record<string,unknown>; target?:Record<string,unknown>; actor?:string}){await initializeEnterpriseArchitectureScientist();const db=getPostgresPool();const assessment=await db.query('SELECT * FROM glorifier_architecture_assessments WHERE id=$1',[input.assessmentId]);if(!assessment.rows[0])throw new Error('architecture assessment not found');const governance=await governRevenueAction({machine:'other',actionType:'propose',objective:input.objective,capability:input.capability||'architecture-review',evidenceRefs:input.evidenceRefs||assessment.rows[0].evidence_refs||[],reversible:true,actor:input.actor||'geas'});const id='geic-'+crypto.randomUUID();await db.query('INSERT INTO glorifier_architecture_improvement_cycles(id,assessment_id,governance_event_id,governance_cycle_id,status,baseline,target,verification) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[id,input.assessmentId,governance.id,governance.governanceCycleId,governance.status,JSON.stringify(input.baseline||{}),JSON.stringify(input.target||{}),JSON.stringify({status:'pending-human-approval-and-implementation',measurableVerificationRequired:true})]);await db.query("UPDATE glorifier_architecture_assessments SET status='governed' WHERE id=$1",[input.assessmentId]);return{id,assessmentId:input.assessmentId,governance,baseline:input.baseline||{},target:input.target||{},verification:{status:'pending-human-approval-and-implementation',measurableVerificationRequired:true}};}
export async function listArchitectureImprovementCycles(limit=50){await initializeEnterpriseArchitectureScientist();const r=await getPostgresPool().query('SELECT * FROM glorifier_architecture_improvement_cycles ORDER BY created_at DESC LIMIT $1',[Math.max(1,Math.min(200,limit))]);return r.rows;}
