import { getPostgresPool } from './db/postgres';
import { aiOrchestrator } from './ai/orchestrator';
import { getGlorifierAiTrustStandard, getGlorifierAiTrustControls } from './ai/trust-standard';
import { getIso42001AlignmentTargets } from './iso-integration';

const query = (text: string, values?: unknown[]) => getPostgresPool().query(text, values);

export type IsoScientistStatus = 'observed' | 'gap-identified' | 'needs-evidence' | 'human-review';

export interface IsoResearchRun {
  id: string;
  standard: string;
  status: IsoScientistStatus;
  scope: string;
  findings: string[];
  gaps: string[];
  evidencePlan: string[];
  riskQuestions: string[];
  lifecycleQuestions: string[];
  improvementActions: string[];
  sources: string[];
  aiAssistanceRecord: string;
  createdAt: string;
  metadata: Record<string, unknown>;
}

let initialized = false;

export async function initializeIsoScientistRegistry() {
  if (initialized) return;
  await query(`
    CREATE TABLE IF NOT EXISTS glorifier_iso_scientist_runs (
      id TEXT PRIMARY KEY,
      standard TEXT NOT NULL,
      status TEXT NOT NULL,
      scope TEXT NOT NULL,
      findings JSONB NOT NULL DEFAULT '[]'::jsonb,
      gaps JSONB NOT NULL DEFAULT '[]'::jsonb,
      evidence_plan JSONB NOT NULL DEFAULT '[]'::jsonb,
      risk_questions JSONB NOT NULL DEFAULT '[]'::jsonb,
      lifecycle_questions JSONB NOT NULL DEFAULT '[]'::jsonb,
      improvement_actions JSONB NOT NULL DEFAULT '[]'::jsonb,
      sources JSONB NOT NULL DEFAULT '[]'::jsonb,
      ai_assistance_record TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      metadata JSONB NOT NULL DEFAULT '{}'::jsonb
    )
  `);
  await query(`CREATE INDEX IF NOT EXISTS idx_glorifier_iso_scientist_runs_created ON glorifier_iso_scientist_runs(created_at DESC)`);
  initialized = true;
}

function arr(value: unknown): string[] {
  return Array.isArray(value) ? value.map(String).filter(Boolean) : [];
}

function parse(text: string): Record<string, unknown> {
  try { return JSON.parse(text); } catch {}
  const m = text.match(/\\{[\\s\\S]*\\}/);
  if (m) try { return JSON.parse(m[0]); } catch {}
  return {};
}

export async function runIsoScientistResearch(input: {
  scope?: string;
  evidence?: string[];
  knownGaps?: string[];
  actor?: string;
}) {
  const scope = input.scope || 'GLORIFIER AI orchestration platform';
  const evidence = arr(input.evidence);
  const knownGaps = arr(input.knownGaps);
  const targets = getIso42001AlignmentTargets();
  const controls = getGlorifierAiTrustControls();

  const system = [
    'You are GLORIFIER ISO AI Scientist, an AI-assisted AI governance and standards research agent.',
    'Analyze ISO/IEC 42001:2023 alignment using only the supplied GLORIFIER evidence and explicitly identified standards information.',
    'Do not claim ISO certification, conformity, accreditation, or official ISO endorsement.',
    'Do not invent ISO clauses, requirements, evidence, audits, or standards citations.',
    'Treat missing evidence as a gap or evidence need, never as proof of noncompliance.',
    'Distinguish internal GLORIFIER framework conformance from independent certification.',
    'Return JSON keys: status, findings, gaps, evidencePlan, riskQuestions, lifecycleQuestions, improvementActions, sources.'
  ].join('\\n');

  const prompt = [
    `Scope: ${scope}`,
    `GLORIFIER GATS controls: ${JSON.stringify(controls)}`,
    `Current ISO alignment targets: ${JSON.stringify(targets)}`,
    `Evidence supplied: ${JSON.stringify(evidence)}`,
    `Known gaps supplied: ${JSON.stringify(knownGaps)}`,
    'Assess governance, risk, lifecycle, transparency, monitoring, documentation, human oversight and continual-improvement evidence.',
    'Return conservative findings suitable for human review.'
  ].join('\\n');

  const response = await aiOrchestrator.resilientGenerate({
    messages: [{ role: 'system', content: system }, { role: 'user', content: prompt }],
    evaluate: true
  });

  const p = parse(response.text);
  const allowed = ['observed','gap-identified','needs-evidence','human-review'];
  const status = allowed.includes(String(p.status)) ? String(p.status) as IsoScientistStatus : 'human-review';
  const record: IsoResearchRun = {
    id: `isr-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,
    standard: 'ISO/IEC 42001:2023',
    status,
    scope,
    findings: arr(p.findings),
    gaps: arr(p.gaps),
    evidencePlan: arr(p.evidencePlan),
    riskQuestions: arr(p.riskQuestions),
    lifecycleQuestions: arr(p.lifecycleQuestions),
    improvementActions: arr(p.improvementActions),
    sources: arr(p.sources),
    aiAssistanceRecord: `AI-assisted ISO research generated by ${response.provider}:${response.model}; independent assessment/certification not performed.`,
    createdAt: new Date().toISOString(),
    metadata: {
      actor: input.actor || 'human-owner',
      provider: response.provider,
      model: response.model,
      evaluation: response.evaluation || null,
      certificationClaimAllowed: false,
      independentAuditPerformed: false,
      evidenceCount: evidence.length,
      knownGapCount: knownGaps.length,
      policy: {
        internalAlignmentOnly: true,
        isoCertificationNotClaimed: true,
        missingEvidenceIsNotNegativeEvidence: true,
        humanReviewRequired: true
      }
    }
  };

  await query(
    `INSERT INTO glorifier_iso_scientist_runs
      (id,standard,status,scope,findings,gaps,evidence_plan,risk_questions,lifecycle_questions,improvement_actions,sources,ai_assistance_record,metadata)
     VALUES ($1,$2,$3,$4,$5::jsonb,$6::jsonb,$7::jsonb,$8::jsonb,$9::jsonb,$10::jsonb,$11::jsonb,$12,$13::jsonb)`,
    [record.id, record.standard, record.status, record.scope, JSON.stringify(record.findings), JSON.stringify(record.gaps), JSON.stringify(record.evidencePlan), JSON.stringify(record.riskQuestions), JSON.stringify(record.lifecycleQuestions), JSON.stringify(record.improvementActions), JSON.stringify(record.sources), record.aiAssistanceRecord, JSON.stringify(record.metadata)]
  );
  return record;
}

export async function listIsoScientistRuns(limit = 50) {
  const result = await query(`SELECT id,standard,status,scope,findings,gaps,evidence_plan AS "evidencePlan",risk_questions AS "riskQuestions",lifecycle_questions AS "lifecycleQuestions",improvement_actions AS "improvementActions",sources,ai_assistance_record AS "aiAssistanceRecord",created_at AS "createdAt",metadata FROM glorifier_iso_scientist_runs ORDER BY created_at DESC LIMIT $1`, [Math.max(1, Math.min(100, limit))]);
  return result.rows;
}

export function getIsoScientistPolicy() {
  return {
    agentRole: 'iso-ai-scientist',
    standard: 'ISO/IEC 42001:2023',
    purpose: 'AI governance, risk, lifecycle, evidence and continual-improvement research.',
    internalAlignmentOnly: true,
    isoCertificationClaimAllowed: false,
    independentAuditPerformed: false,
    missingEvidenceIsNotNegativeEvidence: true,
    humanReviewRequired: true
  };
}
