import { createHash, randomUUID } from 'node:crypto';
import { getPostgresPool } from '../db/postgres';
import { GLORIFIER_ARCHITECTURE_MODEL } from './glorifier-architecture';

export type ArchitectureDomain = 'enterprise-architecture'|'cloud'|'ai'|'data'|'cybersecurity'|'networking'|'software'|'platform-engineering'|'observability'|'reliability'|'finops'|'iot'|'edge'|'blockchain'|'integration'|'governance'|'emerging-technology';
export type EvidenceClass = 'observed-fact'|'analysis'|'recommendation';
export type DriftStatus = 'aligned'|'partial'|'drift'|'unknown';
export type RiskLevel = 'low'|'medium'|'high'|'critical';
export type EvidenceStatus = 'verified'|'not-observed'|'unavailable';

export interface ArchitectureSource { id:string; authority:string; domain:ArchitectureDomain; url:string; patternIds:string[]; cadenceHours:number; }
export interface SourceObservation { sourceId:string; ok:boolean; status:number|null; contentHash:string|null; observedAt:string; evidenceExcerpt:string|null; evidenceStatus:EvidenceStatus; error?:string; }
export interface ArchitecturePattern { id:string; title:string; domain:ArchitectureDomain; evidenceClass:'observed-fact'; sourceId:string; evidenceUrl:string; evidenceExcerpt:string; pattern:string; GLORIFIERMapping:string; controlIds:string[]; lastReviewed:string; }
export interface ArchitectureControl { id:string; name:string; family:string; requirement:string; enforcement:'observe'|'gate'|'human-approval'; irreversibleChangeAllowed:false; }
export interface DriftFinding { id:string; controlId:string; status:DriftStatus; severity:RiskLevel; intended:string; observed:string; evidenceRefs:string[]; recommendation:string; createdAt:string; }
export interface ArchitectureEvidence { id:string; sourceId:string; sourceUrl:string; observedAt:string; contentHash:string; excerpt:string; evidenceClass:'observed-fact'; sourceStatus:number; patternIds:string[]; }
export interface ArchitectureScanResult { scanId:string; startedAt:string; completedAt:string; sources:SourceObservation[]; evidence:ArchitectureEvidence[]; patterns:ArchitecturePattern[]; drift:DriftFinding[]; recommendations:string[]; coverage:Record<ArchitectureDomain,{sources:number;observedPatterns:number;status:'covered'|'source-unavailable'|'no-observed-pattern'}>; irreversibleChangesExecuted:false; }
export interface AgentIdentityContract { identityType:'human'|'agent'|'service'|'provider'|'execution'; subject:string; issuer?:string; audience?:string; scope:string[]; delegatedFrom?:string; expiresAt?:string; revocationRef?:string; keyBinding?:string; }
export interface TokenLifecycleContract { issuer:string; audience:string; scope:string[]; issuedAt:string; expiresAt:string; keyId?:string; verificationRequired:boolean; replayProtectionRequired:boolean; revocationRef?:string; }
export interface GovernedActionEvidencePackage { id:string; actorIdentity:string; authorityRef:string; capability:string; policyDecisionRef:string; actionHash:string; executionIdentity:string; provider?:string; model?:string; tool?:string; traceId?:string; evidenceRefs:string[]; outcomeRef?:string; economicImpactRef?:string; verificationStatus:'UNKNOWN'|'VERIFIED'|'PARTIALLY_VERIFIED'|'NOT_VERIFIED'; createdAt:string; }
export interface AgentReliabilityContract { timeoutMs:number; maxRetries:number; circuitBreakerFailures:number; gracefulDegradation:boolean; outputValidationRequired:boolean; idempotencyRequired:boolean; isolationRequired:boolean; humanEscalationForRisk:RiskLevel; }
export interface SovereigntyBoundary { data:string; modelInference:string; infrastructure:string; operator:string; jurisdiction:string; keyCustody:string; controlPlaneDependencies:string[]; evidenceRetention:string; portability:'portable'|'partial'|'unknown'; exitStrategy:string; }
export interface AIImpactAssessment { id:string; lifecycleStage:'design'|'build'|'evaluate'|'deploy'|'operate'|'monitor'|'retire'; intendedPurpose:string; foreseeableUse:string[]; affectedParties:string[]; risks:string[]; dataSources:string[]; humanOversight:string; evidenceRefs:string[]; reassessmentTrigger:string; createdAt:string; }
export interface FinOpsArchitectureDecision { id:string; workload:string; options:string[]; unitMetric?:string; expectedCost?:Record<string,number>; valueMetric?:string; constraints:string[]; placementTradeoffs:string[]; reversibility:'high'|'medium'|'low'|'unknown'; approvalRequired:boolean; }

const SOURCES:ArchitectureSource[]=[
{id:'microsoft-architecture',authority:'Microsoft',domain:'enterprise-architecture',url:'https://learn.microsoft.com/en-us/azure/architecture/',patternIds:['cross-cutting-cloud-controls'],cadenceHours:168},
{id:'aws-well-architected',authority:'AWS',domain:'cloud',url:'https://aws.amazon.com/architecture/well-architected/',patternIds:['cross-cutting-cloud-controls','reliability-contract'],cadenceHours:168},
{id:'google-architecture',authority:'Google Cloud',domain:'cloud',url:'https://cloud.google.com/architecture',patternIds:['federated-data-access'],cadenceHours:168},
{id:'nist-ai-rmf',authority:'NIST',domain:'ai',url:'https://www.nist.gov/itl/ai-risk-management-framework',patternIds:['ai-lifecycle-risk'],cadenceHours:168},
{id:'nist-ai-agents',authority:'NIST',domain:'ai',url:'https://www.nist.gov/programs-projects/ai-agent-standards-initiative',patternIds:['agent-identity-delegation'],cadenceHours:168},
{id:'nist-csf',authority:'NIST',domain:'cybersecurity',url:'https://www.nist.gov/cyberframework',patternIds:['identity-risk-controls'],cadenceHours:168},
{id:'nist-ssdf',authority:'NIST',domain:'software',url:'https://csrc.nist.gov/Projects/ssdf',patternIds:['software-supply-chain'],cadenceHours:168},
{id:'opentelemetry-semconv',authority:'OpenTelemetry',domain:'observability',url:'https://opentelemetry.io/docs/concepts/semantic-conventions/',patternIds:['vendor-neutral-telemetry','evidence-minimization'],cadenceHours:168},
{id:'finops-focus',authority:'FinOps Foundation',domain:'finops',url:'https://focus.finops.org/',patternIds:['cost-outcome-accounting'],cadenceHours:168},
{id:'cncf-kyverno',authority:'CNCF',domain:'platform-engineering',url:'https://www.cncf.io/projects/kyverno/',patternIds:['policy-as-code'],cadenceHours:168},
{id:'cncf-dapr-agents',authority:'CNCF',domain:'reliability',url:'https://www.cncf.io/projects/dapr/',patternIds:['durable-agent-execution'],cadenceHours:168},
{id:'etsi-eni',authority:'ETSI',domain:'networking',url:'https://www.etsi.org/technical-groups/eni/',patternIds:['federated-continuum','intent-closed-loop'],cadenceHours:168},
{id:'ietf-rfcs',authority:'IETF',domain:'integration',url:'https://www.ietf.org/process/rfcs/',patternIds:['protocol-neutral-interoperability'],cadenceHours:168},
{id:'nist-iot',authority:'NIST',domain:'iot',url:'https://www.nist.gov/programs-projects/nist-cybersecurity-iot-program',patternIds:['iot-device-boundaries'],cadenceHours:336},
{id:'etsi-edge',authority:'ETSI',domain:'edge',url:'https://www.etsi.org/technologies/multi-access-edge-computing',patternIds:['edge-degradation'],cadenceHours:336},
{id:'nist-blockchain',authority:'NIST',domain:'blockchain',url:'https://csrc.nist.gov/pubs/ir/8202/final',patternIds:['selective-trust-anchoring'],cadenceHours:336},
{id:'iso-42001',authority:'ISO',domain:'governance',url:'https://www.iso.org/standard/42001',patternIds:['ai-management-system'],cadenceHours:336},
{id:'w3c-vc',authority:'W3C',domain:'emerging-technology',url:'https://www.w3.org/TR/vc-data-model-2.0/',patternIds:['verifiable-credentials'],cadenceHours:336},
{id:'owasp-agent-control',authority:'OWASP',domain:'cybersecurity',url:'https://genai.owasp.org/resource/agent-control-standard-acs/',patternIds:['runtime-agent-controls'],cadenceHours:168},
{id:'mitre-atlas',authority:'MITRE',domain:'cybersecurity',url:'https://atlas.mitre.org/',patternIds:['adversarial-ai-controls'],cadenceHours:168},
{id:'nist-traceability',authority:'NIST',domain:'data',url:'https://csrc.nist.gov/pubs/ir/8536/final',patternIds:['provenance-graph'],cadenceHours:168}
];

interface PatternDefinition { id:string; title:string; domain:ArchitectureDomain; sourceId:string; pattern:string; GLORIFIERMapping:string; controlIds:string[]; keywords:string[]; }
const P=(id:string,title:string,domain:ArchitectureDomain,sourceId:string,pattern:string,mapping:string,controlIds:string[],keywords:string[]):PatternDefinition=>({id,title,domain,sourceId,pattern,GLORIFIERMapping:mapping,controlIds,keywords});
const PATTERN_DEFINITIONS:PatternDefinition[]=[
P('cross-cutting-cloud-controls','Cross-cutting architecture controls','cloud','aws-well-architected','Treat operational excellence, security, reliability, performance and cost as architecture concerns.','GEAS architecture evidence and drift model',['REL-01','SEC-01','FIN-01'],['security','reliability','cost']),
P('ai-lifecycle-risk','Continuous AI risk lifecycle','ai','nist-ai-rmf','Manage AI trustworthiness and risk across design, development, use and evaluation.','GEAS + AI impact assessment',['AI-01','GOV-01'],['risk','design','development','evaluation']),
P('agent-identity-delegation','Agent identity and authorization','ai','nist-ai-agents','Treat agent identity, authorization, auditing and non-repudiation as explicit architecture concerns.','Agent Identity + Delegation Plane',['SEC-01','AUTH-01'],['identity','authorization','auditing','agent']),
P('identity-risk-controls','Risk-based cybersecurity controls','cybersecurity','nist-csf','Organize cybersecurity outcomes around governance, identification, protection, detection, response and recovery.','GEAS security control crosswalk',['SEC-01','REL-01'],['govern','identify','protect','detect','respond','recover']),
P('software-supply-chain','Secure software supply chain','software','nist-ssdf','Integrate secure software practices throughout the software development lifecycle.','Code Sentinel + provenance graph + release gates',['SUPPLY-01','POL-01'],['software','secure','development','supply chain']),
P('vendor-neutral-telemetry','Common telemetry semantics','observability','opentelemetry-semconv','Use common semantic conventions so telemetry can be correlated across systems.','Agent observability + evidence graph',['OBS-01'],['semantic conventions','telemetry','traces','metrics']),
P('evidence-minimization','Sensitive telemetry minimization','observability','opentelemetry-semconv','Treat telemetry data as potentially sensitive and apply redaction and retention controls.','Evidence minimization policy',['EVID-01'],['sensitive','redact','privacy']),
P('cost-outcome-accounting','Standardized cost and usage accounting','finops','finops-focus','Normalize technology cost and usage data so architecture and economic decisions can be compared.','Revenue Control Plane + cost-per-verified-outcome',['FIN-01'],['cost','usage','standard','AI']),
P('policy-as-code','Declarative policy enforcement','platform-engineering','cncf-kyverno','Encode guardrails as versioned policies and enforce them at platform control points.','GEAS policy engine + deployment gates',['POL-01'],['policy','enforce']),
P('durable-agent-execution','Durable agent execution','reliability','cncf-dapr-agents','Use durable state and recovery patterns for long-running agent workflows.','Daemon + durable work coordinator',['REL-01','STATE-01'],['durable','state','recovery','workflow']),
P('federated-continuum','Federated cloud-network-edge-device continuum','networking','etsi-eni','Use semantic interoperability and common information models across network, edge and compute domains.','Connection Registry + provider-neutral orchestration',['FED-01'],['interoperability','common information','edge']),
P('intent-closed-loop','Intent-driven closed-loop automation','networking','etsi-eni','Translate high-level intent into policy-driven automated actions with assurance.','GEAS policy → governed execution → verification',['POL-01','GOV-01'],['intent','policy','automated','assurance']),
P('protocol-neutral-interoperability','Protocol-neutral interoperability','integration','ietf-rfcs','Prefer explicit, versioned protocols and interoperable interfaces over provider-specific coupling.','A2A/MCP/API adapters + capability registry',['FED-01'],['protocol','interoperability','interface']),
P('iot-device-boundaries','Explicit IoT device security boundaries','iot','nist-iot','Treat device identity, security capabilities and lifecycle boundaries as explicit controls.','Device identity + capability + lifecycle governance',['SEC-01'],['device','identity','lifecycle']),
P('edge-degradation','Edge graceful degradation','edge','etsi-edge','Design edge systems around constrained connectivity, locality and resilient operation.','Degraded-mode contracts',['REL-01','FED-01'],['edge','connectivity','resilience']),
P('selective-trust-anchoring','Selective distributed trust anchoring','blockchain','nist-blockchain','Use distributed ledger concepts selectively where multi-party integrity or provenance requires them.','Optional external receipt/proof anchoring',['EVID-01'],['blockchain','distributed','ledger','trust']),
P('ai-management-system','AI management system','governance','iso-42001','Establish and continually improve a management system for responsible AI governance.','GEAS governance lifecycle + audit evidence',['AI-01','GOV-01'],['management system','AI','continual','governance']),
P('verifiable-credentials','Machine-verifiable credentials','emerging-technology','w3c-vc','Use cryptographically secure, privacy-respecting, machine-verifiable credentials where portable trust is required.','Future portable agent/provider credentials',['AUTH-01','EVID-01'],['verifiable','credential','cryptographically','machine']),
P('runtime-agent-controls','Runtime agent control hooks','cybersecurity','owasp-agent-control','Expose inspectable, traceable and enforceable runtime controls for agents.','GEAS runtime policy adapters',['SEC-01','POL-01','OBS-01'],['agent','runtime','control','traceable']),
P('adversarial-ai-controls','Adversarial AI threat-informed controls','cybersecurity','mitre-atlas','Use threat-informed adversarial AI knowledge to identify and prioritize defensive controls.','Code Sentinel + agent threat model',['SEC-01'],['attack','adversarial','machine learning']),
P('provenance-graph','Cryptographically linked provenance','data','nist-traceability','Link traceability events into a verifiable provenance chain while enabling selective disclosure.','Evidence Graph + provider/model/software provenance',['EVID-01','SUPPLY-01'],['provenance','traceability','cryptographic','selective disclosure']),
P('federated-data-access','Federated data access','data','google-architecture','Use fit-for-purpose governed data access rather than assuming all workloads require centralized movement.','Data governance + provider-neutral connectors',['DATA-01'],['data','access','architecture'])
];

const CONTROLS:ArchitectureControl[]=[
{id:'AI-01',name:'AI lifecycle assessment',family:'ai-governance',requirement:'AI systems and agents have lifecycle impact/risk assessment and reassessment triggers.',enforcement:'gate',irreversibleChangeAllowed:false},
{id:'GOV-01',name:'Human final authority',family:'governance',requirement:'Irreversible external actions require explicit human authorization.',enforcement:'human-approval',irreversibleChangeAllowed:false},
{id:'SEC-01',name:'Scoped agent authority',family:'security',requirement:'Agent identity, tools, data scope and risk must be explicitly bounded.',enforcement:'gate',irreversibleChangeAllowed:false},
{id:'AUTH-01',name:'Identity and delegation',family:'identity',requirement:'Agent identity, delegation scope, audience, expiration and revocation are explicit.',enforcement:'gate',irreversibleChangeAllowed:false},
{id:'OBS-01',name:'Correlated telemetry',family:'observability',requirement:'Agent, model, tool, deployment and outcome telemetry uses stable correlation identifiers.',enforcement:'observe',irreversibleChangeAllowed:false},
{id:'EVID-01',name:'Evidence integrity and minimization',family:'evidence',requirement:'Evidence has provenance, integrity, classification, retention and disclosure controls.',enforcement:'gate',irreversibleChangeAllowed:false},
{id:'FIN-01',name:'Architecture-aware FinOps',family:'finops',requirement:'Material architecture and placement decisions record cost, value, reliability and sovereignty tradeoffs.',enforcement:'gate',irreversibleChangeAllowed:false},
{id:'POL-01',name:'Policy-as-code',family:'platform-governance',requirement:'Applicable controls are machine-evaluable before governed execution.',enforcement:'gate',irreversibleChangeAllowed:false},
{id:'FED-01',name:'Federated interoperability',family:'integration',requirement:'External resources are accessed through explicit contracts, scopes and replaceable adapters.',enforcement:'observe',irreversibleChangeAllowed:false},
{id:'DATA-01',name:'Data boundary awareness',family:'data-governance',requirement:'Data movement and residency/control boundaries are explicitly recorded.',enforcement:'gate',irreversibleChangeAllowed:false},
{id:'REL-01',name:'Agent reliability contract',family:'reliability',requirement:'Timeouts, bounded retries, validation, idempotency, isolation and graceful degradation are defined.',enforcement:'gate',irreversibleChangeAllowed:false},
{id:'STATE-01',name:'Durable execution state',family:'reliability',requirement:'Long-running governed work has durable ownership, checkpoint and recovery semantics.',enforcement:'gate',irreversibleChangeAllowed:false},
{id:'SUPPLY-01',name:'Software and provider provenance',family:'supply-chain',requirement:'Material software, model, provider and deployment dependencies have traceable provenance.',enforcement:'gate',irreversibleChangeAllowed:false}
];

const RECOMMENDATIONS=[
'Make the Architecture Evidence Graph canonical: source → observation → evidence → pattern → control → component → runtime evidence → drift → recommendation → authorization → outcome.',
'Never label a pattern observed unless the current source fetch succeeds and a relevant evidence excerpt is extracted.',
'Add first-class agent identity, delegated authority, capability scope, expiration and revocation semantics.',
'Represent governed actions as evidence packages binding identity, authority, policy, action hash, execution identity, telemetry and outcome.',
'Adopt a versioned OpenTelemetry-compatible execution trace contract while minimizing sensitive GenAI payloads.',
'Normalize technology cost and usage and correlate it with verified outcomes; preserve estimated, observed and verified economic states.',
'Represent architecture drift as desired → declared → deployed → observed → verified, with UNKNOWN when evidence is missing.',
'Use durable coordination for multi-instance Daemon/workflow ownership rather than process-local overlap guards as the only HA mechanism.',
'Record software, model, provider and deployment provenance as a linked graph with selective disclosure where appropriate.',
'Use policy-as-code adapters while retaining human approval for irreversible external actions.',
'Represent sovereignty boundaries explicitly across data, inference, infrastructure, operator, jurisdiction, key custody and control-plane dependencies.',
'Keep blockchain optional and use it only for justified multi-party integrity/proof anchoring.',
'Monitor emerging agent protocols and credentials as compatibility candidates rather than hard dependencies.',
'Do not autonomously implement irreversible production changes from architecture-science findings.'
];

const RELIABILITY_CONTRACT:AgentReliabilityContract={timeoutMs:30000,maxRetries:2,circuitBreakerFailures:5,gracefulDegradation:true,outputValidationRequired:true,idempotencyRequired:true,isolationRequired:true,humanEscalationForRisk:'high'};
const SOVEREIGNTY_DEFAULTS:SovereigntyBoundary={data:'explicit-resource-policy',modelInference:'provider-and-region-specific',infrastructure:'deployment-specific',operator:'human-owner-controlled',jurisdiction:'explicit-required',keyCustody:'explicit-required',controlPlaneDependencies:[],evidenceRetention:'authoritative-application-store',portability:'unknown',exitStrategy:'document-before-material-provider-commitment'};

function stripHtml(input:string){return input.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/\s+/g,' ').trim();}
function extractEvidence(body:string,keywords:string[]){const text=stripHtml(body),lower=text.toLowerCase();let index=-1;for(const k of keywords){const i=lower.indexOf(k.toLowerCase());if(i>=0&&(index<0||i<index))index=i;}return index<0?null:text.slice(Math.max(0,index-240),Math.min(text.length,index+760)).trim();}
async function fetchSource(source:ArchitectureSource):Promise<SourceObservation>{const observedAt=new Date().toISOString();try{const c=new AbortController();const timer=setTimeout(()=>c.abort(),12000);const r=await fetch(source.url,{redirect:'follow',headers:{'User-Agent':'GLORIFIER-GEAS-Architecture-Scientist/2.0',Accept:'text/html,application/xhtml+xml,text/plain'},signal:c.signal});clearTimeout(timer);const body=await r.text();const hash=createHash('sha256').update(body).digest('hex');const keywords=PATTERN_DEFINITIONS.filter(p=>p.sourceId===source.id).flatMap(p=>p.keywords);const excerpt=r.ok?extractEvidence(body,keywords):null;return{sourceId:source.id,ok:r.ok,status:r.status,contentHash:hash,observedAt,evidenceExcerpt:excerpt,evidenceStatus:r.ok&&excerpt?'verified':r.ok?'not-observed':'unavailable',...(r.ok?{}:{error:'authoritative source returned non-2xx'})};}catch(error){return{sourceId:source.id,ok:false,status:null,contentHash:null,observedAt,evidenceExcerpt:null,evidenceStatus:'unavailable',error:error instanceof Error?error.message:'source fetch failed'};}}
function observedPatterns(results:SourceObservation[],reviewedAt:string){const map=new Map(results.map(x=>[x.sourceId,x]));return PATTERN_DEFINITIONS.flatMap(p=>{const s=map.get(p.sourceId);if(!s||s.evidenceStatus!=='verified'||!s.evidenceExcerpt)return[];return[{id:p.id,title:p.title,domain:p.domain,evidenceClass:'observed-fact' as const,sourceId:p.sourceId,evidenceUrl:SOURCES.find(x=>x.id===p.sourceId)?.url||'',evidenceExcerpt:s.evidenceExcerpt,pattern:p.pattern,GLORIFIERMapping:p.GLORIFIERMapping,controlIds:p.controlIds,lastReviewed:reviewedAt}];});}
function buildEvidence(results:SourceObservation[],patterns:ArchitecturePattern[]){const ids=new Map<string,string[]>();for(const p of patterns)ids.set(p.sourceId,[...(ids.get(p.sourceId)||[]),p.id]);return results.flatMap(s=>s.contentHash&&s.evidenceExcerpt&&s.evidenceStatus==='verified'&&s.status?[{id:'evidence-'+s.sourceId+'-'+s.contentHash.slice(0,16),sourceId:s.sourceId,sourceUrl:SOURCES.find(x=>x.id===s.sourceId)?.url||'',observedAt:s.observedAt,contentHash:s.contentHash,excerpt:s.evidenceExcerpt,evidenceClass:'observed-fact' as const,sourceStatus:s.status,patternIds:ids.get(s.sourceId)||[]}]:[]);}
function coverage(results:SourceObservation[],patterns:ArchitecturePattern[]){const out={} as ArchitectureScanResult['coverage'];for(const domain of [...new Set(SOURCES.map(s=>s.domain))] as ArchitectureDomain[]){const sources=SOURCES.filter(s=>s.domain===domain),ids=new Set(sources.map(s=>s.id)),obs=results.filter(s=>ids.has(s.sourceId)),count=patterns.filter(p=>p.domain===domain).length;out[domain]={sources:sources.length,observedPatterns:count,status:count?'covered':obs.some(o=>o.ok)?'no-observed-pattern':'source-unavailable'};}return out;}
function drift():DriftFinding[]{const t=new Date().toISOString();return[
{id:'drift-agent-identity',controlId:'AUTH-01',status:'partial',severity:'high',intended:'Agents have explicit identity, delegation scope, audience, expiration and revocation semantics.',observed:'Scoped agent authorization exists, but identity/delegation is not universal across execution surfaces.',evidenceRefs:['nist-ai-agents','owasp-agent-control'],recommendation:'Adopt AgentIdentityContract for governed agent actions.',createdAt:t},
{id:'drift-telemetry-contract',controlId:'OBS-01',status:'partial',severity:'medium',intended:'Agent/model/tool/deployment/outcome events share stable correlation semantics.',observed:'Agent observability exists, but an architecture-wide OTel-compatible contract is not universal.',evidenceRefs:['opentelemetry-semconv'],recommendation:'Adopt a versioned GEAS telemetry contract.',createdAt:t},
{id:'drift-evidence-minimization',controlId:'EVID-01',status:'partial',severity:'medium',intended:'Evidence has integrity, classification, retention and disclosure controls.',observed:'Evidence/provenance exists, but universal raw-payload minimization is not established.',evidenceRefs:['opentelemetry-semconv','nist-traceability'],recommendation:'Add classification, redaction, retention and selective-disclosure metadata.',createdAt:t},
{id:'drift-policy-enforcement',controlId:'POL-01',status:'partial',severity:'medium',intended:'Applicable policies are machine-evaluable before governed execution.',observed:'GEAS policy evaluation exists; universal runtime/deployment gates are not established.',evidenceRefs:['cncf-kyverno','owasp-agent-control'],recommendation:'Publish versioned policies and add enforcement adapters.',createdAt:t},
{id:'drift-provenance',controlId:'SUPPLY-01',status:'partial',severity:'high',intended:'Software, model, provider and deployment dependencies have traceable provenance.',observed:'Provenance events exist, but a unified linked graph is incomplete.',evidenceRefs:['nist-traceability','nist-ssdf'],recommendation:'Link provider/model/software/deployment provenance into one evidence graph.',createdAt:t},
{id:'drift-finops',controlId:'FIN-01',status:'partial',severity:'low',intended:'Material architecture choices record cost, value and placement tradeoffs.',observed:'Economic controls exist, but normalized usage/cost is not universally tied to architecture decisions.',evidenceRefs:['finops-focus'],recommendation:'Add normalized cost/usage attribution and verified-outcome correlation.',createdAt:t},
{id:'drift-daemon-ha',controlId:'STATE-01',status:'partial',severity:'high',intended:'Long-running governed work has durable ownership, checkpoint and recovery semantics.',observed:'Daemon overlap protection is process-local; durable multi-instance ownership is not universal.',evidenceRefs:['cncf-dapr-agents'],recommendation:'Evaluate durable lease/checkpoint coordination before claiming HA.',createdAt:t},
{id:'drift-architecture-reconciliation',controlId:'GOV-01',status:'partial',severity:'high',intended:'Desired, declared, deployed, observed and verified states are reconciled.',observed:'Architecture models and drift findings exist, but the five-state reconciliation contract is not universal.',evidenceRefs:['microsoft-architecture','aws-well-architected'],recommendation:'Persist five-state reconciliation and never infer compliance from missing evidence.',createdAt:t}
];}

export async function initializeGeasArchitectureScientist(){const db=getPostgresPool();await db.query('CREATE TABLE IF NOT EXISTS geas_architecture_scans(scan_id TEXT PRIMARY KEY,started_at TIMESTAMPTZ NOT NULL,completed_at TIMESTAMPTZ NOT NULL,result JSONB NOT NULL); CREATE TABLE IF NOT EXISTS geas_source_observations(source_id TEXT PRIMARY KEY,observed_at TIMESTAMPTZ NOT NULL,ok BOOLEAN NOT NULL,status INTEGER,content_hash TEXT,evidence_excerpt TEXT,evidence_status TEXT NOT NULL DEFAULT ''unavailable'',error TEXT); CREATE TABLE IF NOT EXISTS geas_architecture_evidence(id TEXT PRIMARY KEY,source_id TEXT NOT NULL,source_url TEXT NOT NULL,observed_at TIMESTAMPTZ NOT NULL,content_hash TEXT NOT NULL,excerpt TEXT NOT NULL,evidence_class TEXT NOT NULL DEFAULT ''observed-fact'',source_status INTEGER NOT NULL,pattern_ids JSONB NOT NULL DEFAULT ''[]''::jsonb); CREATE TABLE IF NOT EXISTS geas_agent_identity_contracts(subject TEXT PRIMARY KEY,contract JSONB NOT NULL,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()); CREATE TABLE IF NOT EXISTS geas_governed_action_evidence(id TEXT PRIMARY KEY,action_hash TEXT NOT NULL,actor_identity TEXT NOT NULL,authority_ref TEXT NOT NULL,capability TEXT NOT NULL,policy_decision_ref TEXT NOT NULL,execution_identity TEXT NOT NULL,provider TEXT,model TEXT,tool TEXT,trace_id TEXT,evidence_refs JSONB NOT NULL DEFAULT ''[]''::jsonb,outcome_ref TEXT,economic_impact_ref TEXT,verification_status TEXT NOT NULL DEFAULT ''UNKNOWN'',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()); CREATE TABLE IF NOT EXISTS geas_architecture_reconciliation(id TEXT PRIMARY KEY,resource_id TEXT NOT NULL,desired JSONB NOT NULL DEFAULT ''{}''::jsonb,declared JSONB NOT NULL DEFAULT ''{}''::jsonb,deployed JSONB NOT NULL DEFAULT ''{}''::jsonb,observed JSONB NOT NULL DEFAULT ''{}''::jsonb,verified JSONB NOT NULL DEFAULT ''{}''::jsonb,status TEXT NOT NULL DEFAULT ''UNKNOWN'',evidence_refs JSONB NOT NULL DEFAULT ''[]''::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());');}

export async function runGeasArchitectureScan():Promise<ArchitectureScanResult>{const scanId='geas-scan-'+randomUUID(),startedAt=new Date().toISOString(),sources=await Promise.all(SOURCES.map(fetchSource)),completedAt=new Date().toISOString(),patterns=observedPatterns(sources,completedAt),evidence=buildEvidence(sources,patterns),result:ArchitectureScanResult={scanId,startedAt,completedAt,sources,evidence,patterns,drift:drift(),recommendations:[...RECOMMENDATIONS],coverage:coverage(sources,patterns),irreversibleChangesExecuted:false};try{await initializeGeasArchitectureScientist();const db=getPostgresPool();await db.query('INSERT INTO geas_architecture_scans(scan_id,started_at,completed_at,result) VALUES($1,$2,$3,$4)',[scanId,startedAt,completedAt,result]);for(const s of sources)await db.query('INSERT INTO geas_source_observations(source_id,observed_at,ok,status,content_hash,evidence_excerpt,evidence_status,error) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(source_id) DO UPDATE SET observed_at=EXCLUDED.observed_at,ok=EXCLUDED.ok,status=EXCLUDED.status,content_hash=EXCLUDED.content_hash,evidence_excerpt=EXCLUDED.evidence_excerpt,evidence_status=EXCLUDED.evidence_status,error=EXCLUDED.error',[s.sourceId,s.observedAt,s.ok,s.status,s.contentHash,s.evidenceExcerpt,s.evidenceStatus,s.error||null]);for(const e of evidence)await db.query('INSERT INTO geas_architecture_evidence(id,source_id,source_url,observed_at,content_hash,excerpt,evidence_class,source_status,pattern_ids) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(id) DO NOTHING',[e.id,e.sourceId,e.sourceUrl,e.observedAt,e.contentHash,e.excerpt,e.evidenceClass,e.sourceStatus,JSON.stringify(e.patternIds)]);}catch{}return result;}

const memory:{last?:ArchitectureScanResult}={};
export async function getLatestGeasArchitectureScan(){try{if(memory.last)return memory.last;await initializeGeasArchitectureScientist();const r=await getPostgresPool().query('SELECT result FROM geas_architecture_scans ORDER BY completed_at DESC LIMIT 1');if(r.rows[0]?.result){memory.last=r.rows[0].result as ArchitectureScanResult;return memory.last;}}catch{}return null;}
export function getGeasArchitectureModel(){return{version:'GEAS-ARCHITECTURE-SCIENTIST-2.0',operatingRule:'GEAS may observe, compare, explain, prioritize and recommend; it must not autonomously apply irreversible production changes.',sourcePolicy:'Only curated authoritative public sources are accepted as architecture evidence.',evidencePolicy:'Observed facts require successful source observation plus extracted evidence. Analysis and recommendations remain distinct.',unknownPolicy:'Missing or unavailable evidence remains UNKNOWN; no compliance is inferred from absence of evidence.',architectureStateModel:['desired','declared','deployed','observed','verified'],domains:[...new Set(SOURCES.map(s=>s.domain))],sources:SOURCES,patterns:PATTERN_DEFINITIONS,controls:CONTROLS,drift:drift(),reliabilityContract:RELIABILITY_CONTRACT,sovereigntyDefaults:SOVEREIGNTY_DEFAULTS,aiLifecycle:['design','build','evaluate','deploy','operate','monitor','retire'],architectureBaseline:GLORIFIER_ARCHITECTURE_MODEL,recommendations:RECOMMENDATIONS,newCapabilities:['agent-identity-delegation','governed-action-evidence-package','evidence-graph','five-state-architecture-reconciliation','otel-compatible-trace-contract','evidence-minimization','provenance-graph','cost-to-verified-outcome','durable-execution-coordination','policy-as-code-adapters','verifiable-credentials-research']};}
export function getGeasArchitectureSources(){return SOURCES;}
export function getGeasArchitecturePatterns(){return PATTERN_DEFINITIONS;}
export function getGeasArchitectureControls(){return CONTROLS;}
export function getGeasArchitectureReliabilityContract(){return RELIABILITY_CONTRACT;}
export function getGeasSovereigntyDefaults(){return SOVEREIGNTY_DEFAULTS;}
export function createAgentIdentityContract(input:Omit<AgentIdentityContract,'identityType'>&{identityType?:AgentIdentityContract['identityType']}):AgentIdentityContract{return{identityType:input.identityType||'agent',...input};}
export async function persistAgentIdentityContract(contract:AgentIdentityContract){await initializeGeasArchitectureScientist();await getPostgresPool().query('INSERT INTO geas_agent_identity_contracts(subject,contract) VALUES($1,$2) ON CONFLICT(subject) DO UPDATE SET contract=EXCLUDED.contract,updated_at=NOW()',[contract.subject,JSON.stringify(contract)]);return contract;}
export function createTokenLifecycleContract(input:Omit<TokenLifecycleContract,'verificationRequired'|'replayProtectionRequired'>&Partial<Pick<TokenLifecycleContract,'verificationRequired'|'replayProtectionRequired'>>):TokenLifecycleContract{return{verificationRequired:true,replayProtectionRequired:true,...input};}
export function createGovernedActionEvidencePackage(input:Omit<GovernedActionEvidencePackage,'id'|'actionHash'|'createdAt'|'verificationStatus'>&{verificationStatus?:GovernedActionEvidencePackage['verificationStatus']}):GovernedActionEvidencePackage{const canonical=JSON.stringify({actorIdentity:input.actorIdentity,authorityRef:input.authorityRef,capability:input.capability,policyDecisionRef:input.policyDecisionRef,executionIdentity:input.executionIdentity,provider:input.provider,model:input.model,tool:input.tool,traceId:input.traceId,evidenceRefs:input.evidenceRefs});return{...input,id:'gae-'+randomUUID(),actionHash:createHash('sha256').update(canonical).digest('hex'),verificationStatus:input.verificationStatus||'UNKNOWN',createdAt:new Date().toISOString()};}
export async function persistGovernedActionEvidencePackage(pkg:GovernedActionEvidencePackage){await initializeGeasArchitectureScientist();await getPostgresPool().query('INSERT INTO geas_governed_action_evidence(id,action_hash,actor_identity,authority_ref,capability,policy_decision_ref,execution_identity,provider,model,tool,trace_id,evidence_refs,outcome_ref,economic_impact_ref,verification_status,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16) ON CONFLICT(id) DO NOTHING',[pkg.id,pkg.actionHash,pkg.actorIdentity,pkg.authorityRef,pkg.capability,pkg.policyDecisionRef,pkg.executionIdentity,pkg.provider||null,pkg.model||null,pkg.tool||null,pkg.traceId||null,JSON.stringify(pkg.evidenceRefs),pkg.outcomeRef||null,pkg.economicImpactRef||null,pkg.verificationStatus,pkg.createdAt]);return pkg;}
export function createAIImpactAssessment(input:Omit<AIImpactAssessment,'id'|'createdAt'>):AIImpactAssessment{return{...input,id:'impact-'+randomUUID(),createdAt:new Date().toISOString()};}
export function createFinOpsArchitectureDecision(input:Omit<FinOpsArchitectureDecision,'id'>):FinOpsArchitectureDecision{return{...input,id:'finops-'+randomUUID(),approvalRequired:input.approvalRequired||input.reversibility!=='high'};}
export async function persistArchitectureReconciliation(input:{id?:string;resourceId:string;desired:Record<string,unknown>;declared:Record<string,unknown>;deployed:Record<string,unknown>;observed:Record<string,unknown>;verified:Record<string,unknown>;status?:string;evidenceRefs:string[]}){const id=input.id||'recon-'+randomUUID(),status=input.status||(Object.keys(input.verified).length?'OBSERVED':'UNKNOWN');await initializeGeasArchitectureScientist();await getPostgresPool().query('INSERT INTO geas_architecture_reconciliation(id,resource_id,desired,declared,deployed,observed,verified,status,evidence_refs) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[id,input.resourceId,JSON.stringify(input.desired),JSON.stringify(input.declared),JSON.stringify(input.deployed),JSON.stringify(input.observed),JSON.stringify(input.verified),status,JSON.stringify(input.evidenceRefs)]);return{id,...input,status};}

let scannerTimer:ReturnType<typeof setInterval>|undefined;
export function startGeasArchitectureScientistDaemon(){if(scannerTimer)return;const enabled=String(process.env.GEAS_ARCHITECTURE_SCAN_ENABLED||'true').toLowerCase()!=='false';if(!enabled)return;const hours=Math.max(1,Number(process.env.GEAS_ARCHITECTURE_SCAN_INTERVAL_HOURS||24));void runGeasArchitectureScan().catch(error=>console.warn('[GEAS] initial architecture scan deferred:',error instanceof Error?error.message:error));scannerTimer=setInterval(()=>void runGeasArchitectureScan().catch(error=>console.warn('[GEAS] scheduled architecture scan deferred:',error instanceof Error?error.message:error)),hours*60*60*1000);scannerTimer.unref?.();}
