import React,{useEffect,useState} from 'react';
import {RefreshCw,PlayCircle,Search,ShieldCheck} from 'lucide-react';

export const OpportunityDiscoveryDashboard:React.FC=()=>{
 const [status,setStatus]=useState<any>(null); const [loading,setLoading]=useState(false); const [message,setMessage]=useState('');
 const load=async()=>{try{const r=await fetch('/api/opportunities/24x7/status',{cache:'no-store'}); if(!r.ok) throw new Error('Discovery status unavailable'); setStatus(await r.json());}catch(e){setMessage(e instanceof Error?e.message:'Unable to load discovery status');}};
 useEffect(()=>{void load(); const id=window.setInterval(()=>void load(),30000); return()=>window.clearInterval(id)},[]);
 const run=async()=>{setLoading(true);setMessage('');try{const r=await fetch('/api/opportunities/24x7/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({actor:'human-owner'})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Discovery run failed');setMessage('Discovery cycle started and evidence was recorded.');await load()}catch(e){setMessage(e instanceof Error?e.message:'Discovery run failed')}finally{setLoading(false)}};
 return <section className="space-y-5"><div className="flex items-center justify-between"><div><div className="flex items-center gap-2"><Search className="h-5 w-5 text-emerald-400"/><h2 className="text-xl font-bold">24/7 Discovery</h2></div><p className="text-xs text-slate-400 mt-1">Continuous evidence-first discovery. Opportunities and estimated value never become verified revenue automatically.</p></div><button onClick={()=>void run()} disabled={loading} className="inline-flex items-center gap-2 rounded-md border border-emerald-500/30 px-3 py-2 text-xs text-emerald-300 disabled:opacity-50"><PlayCircle className="h-4 w-4"/>{loading?'Running…':'Run cycle'}</button></div>
 {message&&<div className="rounded-md border border-slate-800 p-3 text-xs text-slate-300">{message}</div>}
 <div className="grid grid-cols-1 md:grid-cols-3 gap-3">{[['Status',status?.status||'Loading'],['Findings',status?.findingsCount??status?.findingCount??'—'],['Last run',status?.lastRunAt?new Date(status.lastRunAt).toLocaleString():'—']].map(([k,v])=><div key={String(k)} className="rounded-md border border-slate-800 bg-slate-900/50 p-4"><div className="text-[10px] uppercase text-slate-500">{k}</div><div className="mt-1 text-lg font-semibold">{String(v)}</div></div>)}</div>
 <div className="rounded-md border border-emerald-500/20 bg-emerald-500/5 p-4 text-xs text-slate-300"><ShieldCheck className="inline h-4 w-4 mr-2 text-emerald-400"/>Discovery is evidence-producing only; human authorization is required before consequential execution.</div>
 <button onClick={()=>void load()} className="inline-flex items-center gap-2 text-xs text-slate-500 hover:text-slate-200"><RefreshCw className="h-3.5 w-3.5"/>Refresh status</button></section>
};