import React,{useEffect,useState}from'react';import{RefreshCw,ShieldCheck,Wallet,Database,CheckCircle2,AlertTriangle}from'lucide-react';
type EconomicEvent={id?:number;event_id?:string;provider?:string;provider_transaction_id?:string;currency?:string;amount_minor?:number;status?:string;created_at?:string};
type DataItem={id:string;name:string;category:string;status:string;detail:string;configurationStatus:string;verificationStatus:'verified'|'not-verified';verificationEvidence?:string|null;publicUrl?:string};
type DataStatus={generatedAt:string;summary:{total:number;verified:number;notVerified:number;configured:number;needsConfiguration:number};data:DataItem[]};
async function getJson<T>(url:string):Promise<T>{const response=await fetch(url,{cache:'no-store'});const bodyText=await response.text();let body:any;try{body=JSON.parse(bodyText)}catch{throw new Error(response.ok?'Server returned non-JSON data':`API error ${response.status}: ${bodyText.slice(0,80)}`)}if(!response.ok)throw new Error(body?.error||`API error ${response.status}`);return body as T}
export const RevenueVerifiedDashboard:React.FC=()=>{const[events,setEvents]=useState<EconomicEvent[]>([]);const[dataStatus,setDataStatus]=useState<DataStatus|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
const load=async()=>{setLoading(true);setError('');try{const[revenue,status]=await Promise.all([getJson<{revenue:EconomicEvent[]}>('/api/economic-os/verified-revenue'),getJson<DataStatus>('/api/data-status')]);setEvents(revenue.revenue||[]);setDataStatus(status)}catch(e){setError(e instanceof Error?e.message:'Unable to load GLORIFIER live economic data')}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
return <section className="space-y-5"><div className="flex items-center justify-between"><div><div className="flex items-center gap-2"><Wallet className="h-5 w-5"/><h2 className="text-xl font-bold">GLORIFIER Live Economic Data</h2></div><p className="text-xs text-slate-400 mt-1">Live control view of economic records and integration truth labels. Verified means evidence-backed; configured does not mean verified.</p></div><button onClick={()=>void load()} className="p-2 text-slate-400 hover:text-white" aria-label="Refresh"><RefreshCw className={loading?'h-4 w-4 animate-spin':'h-4 w-4'}/></button></div>
<div className="grid grid-cols-2 md:grid-cols-5 gap-2">{[['Total',dataStatus?.summary.total??'—'],['Verified',dataStatus?.summary.verified??'—'],['Not verified',dataStatus?.summary.notVerified??'—'],['Configured',dataStatus?.summary.configured??'—'],['Needs configuration',dataStatus?.summary.needsConfiguration??'—']].map(([label,value])=><div key={String(label)} className="border border-slate-800 p-3"><div className="text-[10px] uppercase tracking-wider text-slate-500">{label}</div><div className="text-lg font-semibold mt-1">{value}</div></div>)}</div>
<div className="border border-emerald-500/20 bg-emerald-500/5 p-4 text-xs"><ShieldCheck className="inline h-4 w-4 mr-2"/>Economic truth: only qualifying externally evidenced settlement records enter verified revenue. Estimates, offers, invoices, balances, usage, configuration and connection status remain separate.</div>
{error&&<div className="border border-rose-500/20 p-3 text-xs text-rose-300"><AlertTriangle className="inline h-4 w-4 mr-2"/>{error}</div>}
<div className="border border-slate-800"><div className="p-3 border-b border-slate-800 font-semibold flex items-center gap-2"><Database className="h-4 w-4"/>Verified Economic Events</div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-b border-slate-800 text-slate-500"><tr><th className="p-3">Reference</th><th className="p-3">Provider</th><th className="p-3">Amount</th><th className="p-3">Currency</th><th className="p-3">Truth</th><th className="p-3">Created</th></tr></thead><tbody>{events.length===0?<tr><td colSpan={6} className="p-6 text-center text-slate-500">No verified revenue events recorded.</td></tr>:events.map((x,i)=><tr key={x.id||x.event_id||i} className="border-b border-slate-900"><td className="p-3">{x.provider_transaction_id||x.event_id||'—'}</td><td className="p-3">{x.provider||'—'}</td><td className="p-3 font-semibold">{((x.amount_minor||0)/100).toFixed(2)}</td><td className="p-3">{x.currency||'—'}</td><td className="p-3"><span className="inline-flex items-center gap-1"><CheckCircle2 className="h-3 w-3"/>Verified</span></td><td className="p-3 text-slate-500">{x.created_at?new Date(x.created_at).toLocaleString():'—'}</td></tr>)}</tbody></table></div></div>
<div className="border border-slate-800"><div className="p-3 border-b border-slate-800 font-semibold">All Connected / Available Data — Truth & Configuration Labels</div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-b border-slate-800 text-slate-500"><tr><th className="p-3">Data source</th><th className="p-3">Category</th><th className="p-3">Configuration</th><th className="p-3">Truth</th><th className="p-3">Evidence</th></tr></thead><tbody>{dataStatus?.data.map(item=><tr key={item.id} className="border-b border-slate-900"><td className="p-3"><div className="font-medium">{item.name}</div><div className="text-[11px] text-slate-500">{item.detail}</div></td><td className="p-3">{item.category}</td><td className="p-3">{item.configurationStatus}</td><td className="p-3">{item.verificationStatus}</td><td className="p-3">{item.verificationEvidence||'None recorded'}</td></tr>)}</tbody></table></div></div>
<div className="text-[11px] text-slate-500">Last synchronized: {dataStatus?.generatedAt?new Date(dataStatus.generatedAt).toLocaleString():'—'} · Human owner retains final authority over consequential actions.</div></section>};